"""
Sample data that mimics real Procore API responses
Used for demo/testing without API credentials
"""

SAMPLE_RFIS = [
    {
        "id": 1,
        "number": "001",
        "subject": "Ceiling height clarification at Level 12",
        "status": "open",
        "priority": "High",
        "cost_impact": "TBD",
        "schedule_impact": "Yes",
        "location": "Level 12 - Core",
        "ball_in_court": {"name": "HKS Architects"},
        "created_by": {"name": "Anthony Buonantuono"},
        "created_at": "2026-01-10T10:00:00Z",
        "due_date": "2026-01-17",
        "assignee": {"name": "Mike Chen"}
    },
    {
        "id": 2,
        "number": "002",
        "subject": "Door hardware specification for Suite 1420",
        "status": "open",
        "priority": "Normal",
        "cost_impact": "$2,400",
        "schedule_impact": "No",
        "location": "Level 14 - Suite 1420",
        "ball_in_court": {"name": "Owner's Rep"},
        "created_by": {"name": "Sarah Johnson"},
        "created_at": "2026-01-08T14:30:00Z",
        "due_date": "2026-01-15",
        "assignee": {"name": "Sarah Johnson"}
    },
    {
        "id": 3,
        "number": "003",
        "subject": "MEP coordination conflict at elevator lobby",
        "status": "closed",
        "priority": "High",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 12 - Elevator Lobby",
        "ball_in_court": {"name": "GC"},
        "created_by": {"name": "Mike Chen"},
        "created_at": "2026-01-05T09:00:00Z",
        "due_date": "2026-01-12",
        "closed_at": "2026-01-11T16:00:00Z",
        "assignee": {"name": "Anthony Buonantuono"}
    },
    {
        "id": 4,
        "number": "004",
        "subject": "Millwork finish color confirmation",
        "status": "open",
        "priority": "Normal",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 14 - Reception",
        "ball_in_court": {"name": "Interior Designer"},
        "created_by": {"name": "Anthony Buonantuono"},
        "created_at": "2026-01-15T11:00:00Z",
        "due_date": "2026-01-22",
        "assignee": {"name": "Mike Chen"}
    },
    {
        "id": 5,
        "number": "005",
        "subject": "Fire rating for corridor partition",
        "status": "open",
        "priority": "High",
        "cost_impact": "TBD",
        "schedule_impact": "Yes",
        "location": "Level 11 - Corridor B",
        "ball_in_court": {"name": "HKS Architects"},
        "created_by": {"name": "Sarah Johnson"},
        "created_at": "2026-01-03T08:00:00Z",
        "due_date": "2026-01-10",
        "assignee": {"name": "Sarah Johnson"}
    },
    {
        "id": 6,
        "number": "006",
        "subject": "Acoustical ceiling grid layout",
        "status": "draft",
        "priority": "Low",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 11 - Open Office",
        "ball_in_court": {"name": "GC"},
        "created_by": {"name": "Anthony Buonantuono"},
        "created_at": "2026-01-20T10:00:00Z",
        "due_date": "2026-01-27",
        "assignee": {"name": "Anthony Buonantuono"}
    },
    {
        "id": 7,
        "number": "007",
        "subject": "Window sill detail at curtain wall",
        "status": "closed",
        "priority": "Normal",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 12 - Perimeter",
        "ball_in_court": {"name": "GC"},
        "created_by": {"name": "Mike Chen"},
        "created_at": "2026-01-02T09:00:00Z",
        "due_date": "2026-01-09",
        "closed_at": "2026-01-08T14:00:00Z",
        "assignee": {"name": "Mike Chen"}
    },
    {
        "id": 8,
        "number": "008",
        "subject": "Electrical panel relocation request",
        "status": "open",
        "priority": "High",
        "cost_impact": "$8,500",
        "schedule_impact": "Yes",
        "location": "Level 14 - Electrical Room",
        "ball_in_court": {"name": "MEP Engineer"},
        "created_by": {"name": "Sarah Johnson"},
        "created_at": "2026-01-18T13:00:00Z",
        "due_date": "2026-01-25",
        "assignee": {"name": "Sarah Johnson"}
    },
    {
        "id": 9,
        "number": "009",
        "subject": "Sprinkler head placement in conference room",
        "status": "open",
        "priority": "Normal",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 14 - Conference A",
        "ball_in_court": {"name": "Fire Protection"},
        "created_by": {"name": "Mike Chen"},
        "created_at": "2026-01-19T09:00:00Z",
        "due_date": "2026-01-26",
        "assignee": {"name": "Mike Chen"}
    },
    {
        "id": 10,
        "number": "010",
        "subject": "ADA clearance at restroom entry",
        "status": "open",
        "priority": "High",
        "cost_impact": "$1,200",
        "schedule_impact": "No",
        "location": "Level 12 - Restrooms",
        "ball_in_court": {"name": "HKS Architects"},
        "created_by": {"name": "Anthony Buonantuono"},
        "created_at": "2026-01-21T11:00:00Z",
        "due_date": "2026-01-28",
        "assignee": {"name": "Anthony Buonantuono"}
    },
    {
        "id": 11,
        "number": "011",
        "subject": "HVAC diffuser locations per revised plan",
        "status": "closed",
        "priority": "Normal",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Level 11 - Open Office",
        "ball_in_court": {"name": "GC"},
        "created_by": {"name": "Sarah Johnson"},
        "created_at": "2025-12-28T14:00:00Z",
        "due_date": "2026-01-04",
        "closed_at": "2026-01-03T10:00:00Z",
        "assignee": {"name": "Sarah Johnson"}
    },
    {
        "id": 12,
        "number": "012",
        "subject": "Stair handrail finish confirmation",
        "status": "closed",
        "priority": "Low",
        "cost_impact": "None",
        "schedule_impact": "No",
        "location": "Stair A - All Levels",
        "ball_in_court": {"name": "GC"},
        "created_by": {"name": "Mike Chen"},
        "created_at": "2025-12-20T08:00:00Z",
        "due_date": "2025-12-27",
        "closed_at": "2025-12-24T16:00:00Z",
        "assignee": {"name": "Mike Chen"}
    }
]

SAMPLE_SUBMITTALS = [
    {
        "id": 1,
        "number": "01.01",
        "revision": "0",
        "title": "Door Hardware - Schlage",
        "spec_section": "08 71 00",
        "type": "Product Data",
        "status": "approved",
        "submitted_by": {"name": "ABC Hardware Co"},
        "responsible_contractor": "R&J Construction",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-15",
        "submitted_date": "2026-01-10",
        "approved_date": "2026-01-14",
        "lead_time": "4 weeks"
    },
    {
        "id": 2,
        "number": "01.02",
        "revision": "0",
        "title": "Acoustical Ceiling Tiles - Armstrong",
        "spec_section": "09 51 00",
        "type": "Product Data",
        "status": "pending",
        "submitted_by": {"name": "Ceiling Systems Inc"},
        "responsible_contractor": "Acoustical Ceilings LLC",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-20",
        "submitted_date": "2026-01-12",
        "approved_date": "",
        "lead_time": "3 weeks"
    },
    {
        "id": 3,
        "number": "01.03",
        "revision": "1",
        "title": "Millwork Shop Drawings - Custom Cabinets",
        "spec_section": "06 41 00",
        "type": "Shop Drawing",
        "status": "revise_resubmit",
        "submitted_by": {"name": "Fine Woodworks LLC"},
        "responsible_contractor": "Fine Woodworks LLC",
        "approver": {"name": "Interior Designer"},
        "due_date": "2026-01-18",
        "submitted_date": "2026-01-08",
        "approved_date": "",
        "lead_time": "6 weeks"
    },
    {
        "id": 4,
        "number": "02.01",
        "revision": "0",
        "title": "Paint Colors - Benjamin Moore",
        "spec_section": "09 91 00",
        "type": "Sample",
        "status": "approved",
        "submitted_by": {"name": "Pro Painters Inc"},
        "responsible_contractor": "Pro Painters Inc",
        "approver": {"name": "Interior Designer"},
        "due_date": "2026-01-10",
        "submitted_date": "2026-01-05",
        "approved_date": "2026-01-09",
        "lead_time": "1 week"
    },
    {
        "id": 5,
        "number": "02.02",
        "revision": "0",
        "title": "Carpet Tile - Interface",
        "spec_section": "09 68 00",
        "type": "Sample",
        "status": "pending",
        "submitted_by": {"name": "Flooring Solutions"},
        "responsible_contractor": "Flooring Solutions",
        "approver": {"name": "Interior Designer"},
        "due_date": "2026-01-22",
        "submitted_date": "2026-01-14",
        "approved_date": "",
        "lead_time": "2 weeks"
    },
    {
        "id": 6,
        "number": "03.01",
        "revision": "0",
        "title": "Light Fixtures - Schedule A",
        "spec_section": "26 51 00",
        "type": "Product Data",
        "status": "approved_as_noted",
        "submitted_by": {"name": "Electric Supply Co"},
        "responsible_contractor": "Ace Electric",
        "approver": {"name": "MEP Engineer"},
        "due_date": "2026-01-12",
        "submitted_date": "2026-01-06",
        "approved_date": "2026-01-11",
        "lead_time": "8 weeks"
    },
    {
        "id": 7,
        "number": "03.02",
        "revision": "0",
        "title": "VAV Boxes - Trane",
        "spec_section": "23 36 00",
        "type": "Product Data",
        "status": "pending",
        "submitted_by": {"name": "HVAC Distributors"},
        "responsible_contractor": "Metro HVAC",
        "approver": {"name": "MEP Engineer"},
        "due_date": "2026-01-25",
        "submitted_date": "2026-01-18",
        "approved_date": "",
        "lead_time": "10 weeks"
    },
    {
        "id": 8,
        "number": "04.01",
        "revision": "0",
        "title": "Fire Extinguisher Cabinets",
        "spec_section": "10 44 00",
        "type": "Product Data",
        "status": "rejected",
        "submitted_by": {"name": "Safety Equipment Inc"},
        "responsible_contractor": "R&J Construction",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-08",
        "submitted_date": "2026-01-03",
        "approved_date": "",
        "lead_time": "2 weeks"
    },
    {
        "id": 9,
        "number": "04.02",
        "revision": "0",
        "title": "Exit Signs - LED",
        "spec_section": "10 14 00",
        "type": "Product Data",
        "status": "approved",
        "submitted_by": {"name": "Electric Supply Co"},
        "responsible_contractor": "Ace Electric",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-08",
        "submitted_date": "2026-01-02",
        "approved_date": "2026-01-07",
        "lead_time": "3 weeks"
    },
    {
        "id": 10,
        "number": "05.01",
        "revision": "2",
        "title": "Drywall Partition Details",
        "spec_section": "09 21 16",
        "type": "Shop Drawing",
        "status": "approved",
        "submitted_by": {"name": "Drywall Pros"},
        "responsible_contractor": "Drywall Pros",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-05",
        "submitted_date": "2025-12-28",
        "approved_date": "2026-01-04",
        "lead_time": "1 week"
    },
    {
        "id": 11,
        "number": "05.02",
        "revision": "0",
        "title": "Glass Partition System - Modernus",
        "spec_section": "08 88 00",
        "type": "Shop Drawing",
        "status": "pending",
        "submitted_by": {"name": "Glass Solutions NYC"},
        "responsible_contractor": "Glass Solutions NYC",
        "approver": {"name": "HKS Architects"},
        "due_date": "2026-01-28",
        "submitted_date": "2026-01-20",
        "approved_date": "",
        "lead_time": "12 weeks"
    },
    {
        "id": 12,
        "number": "06.01",
        "revision": "0",
        "title": "Plumbing Fixtures - Kohler",
        "spec_section": "22 40 00",
        "type": "Product Data",
        "status": "approved",
        "submitted_by": {"name": "Metro Plumbing Supply"},
        "responsible_contractor": "AAA Plumbing",
        "approver": {"name": "MEP Engineer"},
        "due_date": "2026-01-10",
        "submitted_date": "2026-01-04",
        "approved_date": "2026-01-09",
        "lead_time": "6 weeks"
    }
]

SAMPLE_DAILY_LOGS = [
    {
        "id": 1,
        "log_date": "2026-01-20",
        "day": "Monday",
        "weather": "Clear, 35°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 12, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 8, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 4, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 6, "company": "Metro HVAC"}
        ],
        "work_performed": "Framing continues on Level 14 offices. MEP rough-in on Level 12 bathrooms.",
        "deliveries": ["Drywall (40 sheets)", "Electrical conduit"],
        "visitors": ["Owner's Rep - site walk"],
        "safety_incidents": [],
        "notes": "On schedule. Level 14 framing 80% complete."
    },
    {
        "id": 2,
        "log_date": "2026-01-21",
        "day": "Tuesday",
        "weather": "Snow, 28°F",
        "weather_delay": True,
        "work_hours": "7:00 AM - 2:00 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 8, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 6, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 2, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 4, "company": "Metro HVAC"}
        ],
        "work_performed": "Interior work only due to weather. Continued electrical rough-in Level 12.",
        "deliveries": [],
        "visitors": [],
        "safety_incidents": [],
        "notes": "Reduced crew due to weather. Early release at 2 PM."
    },
    {
        "id": 3,
        "log_date": "2026-01-22",
        "day": "Wednesday",
        "weather": "Cloudy, 32°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 14, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 10, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 5, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 6, "company": "Metro HVAC"},
            {"trade": "Drywall", "headcount": 8, "company": "Drywall Pros"}
        ],
        "work_performed": "Drywall started on Level 11. Full crew back on site. Completed framing Level 14.",
        "deliveries": ["Drywall (120 sheets)", "Joint compound", "HVAC diffusers"],
        "visitors": ["Fire Marshal - inspection prep"],
        "safety_incidents": [],
        "notes": "Drywall ahead of schedule. Level 11 boarding 25% complete."
    },
    {
        "id": 4,
        "log_date": "2026-01-23",
        "day": "Thursday",
        "weather": "Clear, 38°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 14, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 10, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 5, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 6, "company": "Metro HVAC"},
            {"trade": "Drywall", "headcount": 10, "company": "Drywall Pros"}
        ],
        "work_performed": "Good progress all areas. MEP coordination meeting held. Prepared for DOB inspection.",
        "deliveries": ["Light fixtures (Schedule A)", "Door frames (8)"],
        "visitors": ["Architect - RFI review", "MEP Engineer - coordination"],
        "safety_incidents": [],
        "notes": "DOB inspection scheduled for Friday AM."
    },
    {
        "id": 5,
        "log_date": "2026-01-24",
        "day": "Friday",
        "weather": "Clear, 42°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 12, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 8, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 4, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 5, "company": "Metro HVAC"},
            {"trade": "Drywall", "headcount": 10, "company": "Drywall Pros"}
        ],
        "work_performed": "DOB inspection passed. Framing complete Level 14. Started door frame installation.",
        "deliveries": ["Doors (12)", "Hardware sets"],
        "visitors": ["DOB Inspector - PASSED"],
        "safety_incidents": [],
        "notes": "Inspection passed. On track for Monday taping."
    },
    {
        "id": 6,
        "log_date": "2026-01-27",
        "day": "Monday",
        "weather": "Partly Cloudy, 40°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 10, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 12, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 6, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 8, "company": "Metro HVAC"},
            {"trade": "Drywall", "headcount": 12, "company": "Drywall Pros"},
            {"trade": "Tapers", "headcount": 4, "company": "Drywall Pros"}
        ],
        "work_performed": "Taping started Level 11. Electrical trim Level 12. Plumbing fixtures Level 12.",
        "deliveries": ["Ceiling grid (Level 11)", "Plumbing fixtures"],
        "visitors": [],
        "safety_incidents": [],
        "notes": "Added taping crew. Level 11 drywall 90% complete."
    },
    {
        "id": 7,
        "log_date": "2026-01-28",
        "day": "Tuesday",
        "weather": "Rain, 45°F",
        "weather_delay": False,
        "work_hours": "7:00 AM - 3:30 PM",
        "manpower": [
            {"trade": "Carpenters", "headcount": 10, "company": "R&J Construction"},
            {"trade": "Electricians", "headcount": 12, "company": "Ace Electric"},
            {"trade": "Plumbers", "headcount": 6, "company": "AAA Plumbing"},
            {"trade": "HVAC", "headcount": 8, "company": "Metro HVAC"},
            {"trade": "Drywall", "headcount": 8, "company": "Drywall Pros"},
            {"trade": "Tapers", "headcount": 6, "company": "Drywall Pros"},
            {"trade": "Painters", "headcount": 4, "company": "Pro Painters Inc"}
        ],
        "work_performed": "Painting started Level 12. Taping continues Level 11. Ceiling grid layout.",
        "deliveries": ["Paint (primer + finish)", "Ceiling tiles"],
        "visitors": ["Interior Designer - color review"],
        "safety_incidents": [],
        "notes": "Painters mobilized. Level 12 ready for finishes."
    }
]
